## Importing Modules in Python: Modules and Packages

With the help of modules, I can directly use built-in functions, without writing the code from scratch.

In python, modules and packages help organize and reuse code.

In [2]:
import math
math.sqrt(16)

4.0

In [ ]:
from math import sqrt,pi
print(sqrt(25))
print(pi)


5.0
3.141592653589793


In [ ]:
# import numpy ## if the module is not installed we get "ModuleNotFoundError" so first we need to install the module in order to work with it.
## !pip install numpy 

   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.3 MB 328.9 kB/s eta 0:00:36
   - -------------------------------------- 0.5/12.3 MB 328.9 kB/s eta 0:00:36
   - -------------------------------------- 0.5/12.3 MB 328.9 kB/s eta 0:00:36
   - -------------------------------------- 0.5/12.3 MB 328.9 kB/s eta 0:00:36
   - -------------------------------------- 0.5/12.3 MB 328.9 kB/s eta 0:00:36
   -- ------------------------------------- 0.8/12.3 MB 302.4 kB/s eta 0:00:39
   -- ------------------------------

In [9]:
import numpy as np
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [10]:
my_array = np.array([1,2,3,4,5,6])
print(my_array)

[1 2 3 4 5 6]


In [ ]:
import numpy as np
from numpy import array

squares = array([1,4,9,16,25,36])
print(squares) # array
print([1,2,3,4,5]) # list

[ 1  4  9 16 25 36]
[1, 2, 3, 4, 5]


In [ ]:
# importing all the functions from a module
from math import *
print(sqrt(36))
print(pi)

6.0
3.141592653589793


In [ ]:
## Creating our own custom modules and packages
from package import mymath as math
print(math.addition(2,5))

from package.mymath import addition as add
print(add(5,6))


7
11


In [ ]:
## sub-packages import